// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/wilomendez/Onboarding/create-contact-aws-lambda/models (interfaces: IContactsRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/wilomendez/Onboarding/create-contact-aws-lambda/models"
)

// MockIContactsRepo is a mock of IContactsRepo interface.
type MockIContactsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIContactsRepoMockRecorder
}

// MockIContactsRepoMockRecorder is the mock recorder for MockIContactsRepo.
type MockIContactsRepoMockRecorder struct {
	mock *MockIContactsRepo
}

// NewMockIContactsRepo creates a new mock instance.
func NewMockIContactsRepo(ctrl *gomock.Controller) *MockIContactsRepo {
	mock := &MockIContactsRepo{ctrl: ctrl}
	mock.recorder = &MockIContactsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContactsRepo) EXPECT() *MockIContactsRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIContactsRepo) Create(arg0 models.Contacts) (models.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(models.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIContactsRepoMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIContactsRepo)(nil).Create), arg0)
}
